evidence(\+cancer).
evidence(\+smoker).
evidence(dyspnoea).
evidence(xray("negative")).
evidence(pollution("low")).
----------------
evidence(\+cancer).
evidence(xray("negative")).
evidence(pollution("high")).
evidence(smoker).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(dyspnoea).
evidence(xray("negative")).
evidence(pollution("low")).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(dyspnoea).
evidence(xray("negative")).
evidence(pollution("low")).
----------------
evidence(\+cancer).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(smoker).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(smoker).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(dyspnoea).
evidence(xray("negative")).
evidence(pollution("low")).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(smoker).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(smoker).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(pollution("low")).
evidence(smoker).
evidence(\+dyspnoea).
evidence(xray("positive")).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(smoker).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(dyspnoea).
evidence(xray("negative")).
evidence(pollution("low")).
----------------
evidence(\+cancer).
evidence(dyspnoea).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(smoker).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(xray("negative")).
evidence(pollution("high")).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(smoker).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(smoker).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(smoker).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(dyspnoea).
evidence(xray("negative")).
evidence(pollution("low")).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(dyspnoea).
evidence(pollution("low")).
evidence(xray("positive")).
----------------
evidence(\+cancer).
evidence(pollution("low")).
evidence(smoker).
evidence(\+dyspnoea).
evidence(xray("positive")).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(dyspnoea).
evidence(xray("negative")).
evidence(pollution("low")).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(pollution("low")).
evidence(\+dyspnoea).
evidence(xray("positive")).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(dyspnoea).
evidence(xray("negative")).
evidence(pollution("low")).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(pollution("low")).
evidence(\+dyspnoea).
evidence(xray("positive")).
----------------
evidence(\+cancer).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(smoker).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(dyspnoea).
evidence(pollution("high")).
evidence(smoker).
evidence(xray("positive")).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(dyspnoea).
evidence(xray("negative")).
evidence(pollution("low")).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(smoker).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(smoker).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(dyspnoea).
evidence(xray("negative")).
evidence(pollution("low")).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(pollution("low")).
evidence(smoker).
evidence(\+dyspnoea).
evidence(xray("positive")).
----------------
evidence(\+cancer).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(smoker).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(dyspnoea).
evidence(pollution("low")).
evidence(smoker).
evidence(xray("positive")).
----------------
evidence(\+cancer).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(smoker).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(dyspnoea).
evidence(xray("negative")).
evidence(pollution("low")).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(dyspnoea).
evidence(xray("negative")).
evidence(pollution("low")).
----------------
evidence(\+cancer).
evidence(dyspnoea).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(smoker).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(smoker).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(dyspnoea).
evidence(xray("negative")).
evidence(pollution("low")).
----------------
evidence(\+cancer).
evidence(dyspnoea).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(smoker).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(dyspnoea).
evidence(xray("negative")).
evidence(pollution("low")).
----------------
evidence(\+cancer).
evidence(dyspnoea).
evidence(pollution("low")).
evidence(smoker).
evidence(xray("positive")).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(pollution("low")).
evidence(\+dyspnoea).
evidence(xray("positive")).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(xray("negative")).
evidence(pollution("high")).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(dyspnoea).
evidence(pollution("low")).
evidence(xray("positive")).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(dyspnoea).
evidence(xray("negative")).
evidence(pollution("low")).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(\+dyspnoea).
----------------
evidence(\+smoker).
evidence(dyspnoea).
evidence(xray("negative")).
evidence(cancer).
evidence(pollution("low")).
----------------
evidence(\+cancer).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(smoker).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(dyspnoea).
evidence(pollution("low")).
evidence(xray("positive")).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(smoker).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(dyspnoea).
evidence(pollution("high")).
evidence(smoker).
evidence(xray("positive")).
----------------
evidence(\+cancer).
evidence(dyspnoea).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(smoker).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(dyspnoea).
evidence(xray("negative")).
evidence(pollution("low")).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(pollution("low")).
evidence(\+dyspnoea).
evidence(xray("positive")).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(pollution("low")).
evidence(smoker).
evidence(\+dyspnoea).
evidence(xray("positive")).
----------------
evidence(\+cancer).
evidence(pollution("high")).
evidence(smoker).
evidence(\+dyspnoea).
evidence(xray("positive")).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(pollution("low")).
evidence(\+dyspnoea).
evidence(xray("positive")).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(pollution("low")).
evidence(\+dyspnoea).
evidence(xray("positive")).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(dyspnoea).
evidence(xray("negative")).
evidence(pollution("low")).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(pollution("low")).
evidence(\+dyspnoea).
evidence(xray("positive")).
----------------
evidence(\+cancer).
evidence(dyspnoea).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(smoker).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(smoker).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(pollution("low")).
evidence(\+dyspnoea).
evidence(xray("positive")).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(xray("negative")).
evidence(pollution("low")).
evidence(\+dyspnoea).
----------------
evidence(\+cancer).
evidence(\+smoker).
evidence(dyspnoea).
evidence(xray("negative")).
evidence(pollution("low")).
